site_name: JARVIS Mocap -  Documentation

# Page tree
nav:
  - "Home": "index.md"
  - "Getting Started": 
    - "1. Introduction": "getting_started/1_introduction.md"
    - "2. Exploring the Example Trainingset": "getting_started/2_exploring_example.md"
    - "3. Creating a new Trainingset": "getting_started/3_creating_trainingset.md"
  - "Manual":
    - "1. Introduction": "manual/1_introduction.md"
    - "2. Designing a Setup": "manual/2_mocap_setup_design.md"
    - "3. Setting up the AcquisitionTool": "manual/3_acquisitiontool_setup.md"
    - "4. Recording Calibration Videos": "manual/4_recording_calibration.md"
    - "5. Creating and Labeling Datasets": "manual/5_creating_and_labeling_datasts.md"
  - "Model Database": "model_database/model_database.md"
  - "Downloads": "downloads/downloads.md"

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny


        name: Switch to dark mode
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
  logo: assets/images/logo.png
  favicon: assets/images/logo_color.svg


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - glightbox:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/JARVIS-MoCap"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hueser_timo"
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 


            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.


# Copyright
copyright: "&copy; 2022 Timo Hüser"

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/JARVIS-MoCap"
edit_uri: ""